Interface IAddress
    Property DellAddress1 As String
    Property DellAddress2 As String
    Property DelTown As String
    Property DelCity As String
    Property DelPostCode As String
    Property DelCountry As String
    Property PostalAddress1 As String
    Property PostalAddress2 As String
    Property PostalTown As String
    Property PostalCity As String
    Property PostalPostCode As String
    Property PostalCountry As String
    Property POBOX As String
    Property POBOXPostCode As String
    Property POBOXCity As String
    Property WorkPhone As String
    Property HomePhone As String
    Property MobilePhone As String
    Property Fax As String
    Property Email As String
    Property Url As String
    Property CompanyRegNo As String
    Property VatRegNo As String
    Property Notes As String
    Property Text1 As String
    Property Text2 As String
    Property Text3 As String
    Property Text4 As String
    Property Text5 As String
    Property Text6 As String
    Property Text7 As String
    Property Text8 As String
    Property Text9 As String
    Property Text10 As String
    Property Date1 As String
    Property Date2 As String
    Property Date3 As String
    Property Date4 As String
    Property Date5 As String
    Property Number1 As Decimal?
    Property Number2 As Decimal?
    Property Number3 As Decimal?
    Property Number4 As Decimal?
    Property Number5 As Decimal?
    Property LicenceNo As String
    Property RegNoID As String
End Interface
